### PR TITLE
Bump to latest soc-testsocket-sifive.

### PR DESCRIPTION
**Pull request by richardxia**
This points to https://github.com/sifive/soc-testsocket-sifive/pull/8, which just helps us get this repo pointed to a much more recent version of the dependencies.

Once that PR merges in, I'll update this one to point to the merged commit rather than a branch.

### CODE REVIEW

**Comment by richardxia** [comment]
I had to bump to wake 0.17.1, which caused me to have to make a new release of environment-blockci-sifive.git. This all seems to be working now, so I'm going to merge the soc-testsocket-sifive.git change, and repoint this to the merged commit.

Also, I've added a CHANGELOG.md, much like I did in https://github.com/sifive/environment-blockci-sifive/pull/6.

**Comment by richardxia** [comment]
cc @sistillson 

So, it looks like despite the fact that Travis CI is returning a green checkmark, if you actually look at the console output, it's failing to compile the software test program, and therefore failing to run the RTL simulation. Two questions:

1) Is it failing to compile because of https://github.com/sifive/api-generator-sifive/pull/16? Here is the error message:

    ```
    block-pio-sifive/drivers/metal/sifive_pio.c: In function 'pio_odata_write':
    block-pio-sifive/drivers/metal/sifive_pio.c:15:48: error: 'METAL_PIO_ODATA' undeclared (first use in this function); did you mean 'METAL_PIO_REGBW'?
         unsigned int byte_to_write = (bit >> 3) + (METAL_PIO_ODATA);
                                                    ^~~~~~~~~~~~~~~
                                                    METAL_PIO_REGBW
    ```

2) Can we fix the wake rules such that software compilation failures cause the wake process to exit with non-zero status?

**Comment by richardxia** [comment]
Force-pushed a few more changes to this branch:
- One to bump to the latest api-generator-sifive in order to have the Wake command actually fail if we fail a test
- One to update the driver file to match the new generated header file #define names

I am expecting this branch to (correctly) fail now, but I need to implement an alternative fix to https://github.com/sifive/api-generator-sifive/pull/23 so that the build actually passes.

**Comment by richardxia** [comment]
Previous push failed (as expected), and I am now pointing this branch at https://github.com/sifive/soc-testsocket-sifive/pull/9, which should hopefully pass.

Once we confirm everything is working, I'll merge in https://github.com/sifive/soc-testsocket-sifive/pull/9, and then I'll clean up this PR to point at the merge commit and get all the CHANGELOG stuff updated.

**Comment by richardxia** [comment]
Simulation tests are now passing, but docs are now failing. Working on a fix for that now.

**Comment by richardxia** [comment]
Bumped various wit pointers to commits that have been merged into master and/or tagged on their respective repos. Squashed down the commits, and I think this is now ready for a final (!) review.

**Review by albertchen-sifive — APPROVED** [review]
